name: Build Docker Image

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPOSITORY: xjonathanlei/cloudflare-kv-swap

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(jq -r '.version' ./package.json)
          docker build -t ${DOCKER_REPOSITORY}:${IMAGE_TAG} -f ./Dockerfile .
          docker push ${DOCKER_REPOSITORY}:${IMAGE_TAG}
          docker tag ${DOCKER_REPOSITORY}:${IMAGE_TAG} ${DOCKER_REPOSITORY}:latest
          docker push ${DOCKER_REPOSITORY}:latest
